# Generated by Django 4.0.5 on 2022-06-22 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_servicios_subscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
