# Generated by Django 4.0.5 on 2022-07-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_imagenpost_post_alter_comentarios_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscripcion',
        ),
    ]
