# Generated by Django 4.0.5 on 2022-07-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_delete_subscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenPost',
        ),
    ]
