# Generated by Django 4.0.5 on 2022-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0007_delete_imagenpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='algo', upload_to='media'),
        ),
    ]
