# Generated by Django 4.0.5 on 2022-07-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0010_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='imagen del post', upload_to='blog/'),
        ),
    ]
