# Generated by Django 4.0.5 on 2022-07-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0012_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='DjangoApp/static/DjangoApp/assets/img/blog/blog-1.jpg', upload_to='blog/'),
        ),
    ]
